School Library: Refactor code (Pair Programming)
Samuelwanza/oopschoollibrary pull request #6
Opened 2023-09-18 17:29 UTC by mahdinoori2000

### What is added

- YAGNI, KISS, and DRY rules and Ruby style guide are respected.
- Followed SOLID principles.
- Pay to the "Single-responsibility Principle".
- The role of main.rb is only to start your code and ask the user for the initial choice of options (or to quit).
- Extract some pieces of logic into separate class(es).

2023-09-18 20:53 UTC, skyv26 requested changes
## Hi @mahdinoori2000 and @Samuelwanza , 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNjVhZjBiZjUzZmYxZjI1NGFhNGQ0ZjIyN2FhOTcwNDZlZmUzNmZkMiZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/L422JoNlBBBD42zkQ9/giphy.gif)

## Highlights
- Implement the features ✅ 
- Professional `README` template ✅ 
- Used correct `Gitflow` ✅ 
- Meaningful **Github** commits ✅ 
- Followed *best-practices* ✅ 
- Correct **Semantics** used ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-18 20:53 UTC, skyv26 commented on app.rb
> +  end
- [ ] Please 🙏🏻 follow the ruby best practices, as you can see your functionality inside the two functions is similar except the parameters `true` and `false`. So please use the one function and re-use it again and again, which will help you to achieve more drier code.

2023-09-18 20:53 UTC, skyv26 commented on app.rb
- [ ] Kindly follow the `YAGNI` principle according to which you should remove those things which are not useful and will not contribute to your project advancement. For line number **46** you are returning `nil` and the fact is your application is going to work without using this `keyword`.

2023-09-19 07:28 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @mahdinoori2000  👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- DRY principles have been implemented  ✔
- Code follows best practices ✔
- Correct use of Git Flow ✔
- Linter check is passing ✔
- Descriptive PR title with a good summary ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-19 07:29 UTC, merged